RMSCTIS/Controllers/ResourcesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataAccess_.Contexts;
using DataAccess_.Entities;
using Business.Services;
using Business.Models;
using MVC.Controllers.Bases;

namespace MVC.Controllers
{
    public class ResourcesController : MvcControllerBase
    {
        private readonly IResourceService _resourceService;
		private readonly IUserService _userService;


		public ResourcesController(IResourceService resourceService, IUserService userService)
		{
			_resourceService = resourceService;
			_userService = userService;
		}

		public IActionResult Index()
        {
			List<ResourceModel> resourceList = _resourceService.GetList();

			return View(resourceList);
        }

        public IActionResult Details(int id)
        {
			ResourceModel resource = _resourceService.GetItem(id);
			if (resource == null)
            {
				return View("_Error", "Resource not found!");
			}
            return View(resource);
        }

        // GET: Resources/Create
        public IActionResult Create()
        {
			ViewBag.UserId = new MultiSelectList(_userService.Query().ToList(), "Id", "UserName");
			return View();
		}

      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ResourceModel resource)
        {
            if (ModelState.IsValid)
            {
				var selectedUserIds = resource.UserIdsInput;
				var result = _resourceService.Add(resource);
                if (result.IsSuccessfull)
                {
                    TempData["Message"] = result.Message;
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", result.Message);
            }


            ViewBag.UserId = new MultiSelectList(_userService.Query().ToList(), "Id", "UserName");


            return View(resource);
        }

        // GET: Resources/Edit/5
        public IActionResult Edit(int id)
        {
            ResourceModel resource = _resourceService.GetItem(id);
            if (resource == null)
            {
                return View("_Error", "Resource not found!");
            }
            ViewBag.UserId = new MultiSelectList(_userService.Query().ToList(), "Id", "UserName");
            return View(resource);
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ResourceModel resource)
        {
            if (ModelState.IsValid)
            {
                var result = _resourceService.Update(resource);
                if (result.IsSuccessfull)
                {
                    TempData["Message"] = result.Message;
                    return RedirectToAction(nameof(Details), new { id = resource.Id });
                }
                ModelState.AddModelError("", result.Message);
            }

            ViewBag.UserId = new MultiSelectList(_userService.Query().ToList(), "Id", "UserName");
            return View(resource);
        }

        public IActionResult Delete(int id)
        {
            ResourceModel resource = null;
            if (resource == null)
            {
                return NotFound();
            }
            return View(resource);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
			var result = _resourceService.Delete(id);
			TempData["Message"] = result.Message;
			return RedirectToAction(nameof(Index));
		}
	}
}

RMSCTIS/Controllers/RolesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataAccess_.Contexts;
using DataAccess_.Entities;
using Business.Services;
using Business.Models;
using MVC.Controllers.Bases;

namespace MVC.Controllers
{
    public class RolesController : MvcControllerBase
	{
        private readonly IRoleService _roleService;

        public RolesController(IRoleService roleService)
        {
            _roleService = roleService;
        }

        public IActionResult Index()
        {
            List<RoleModel> roleList = _roleService.Query().ToList();
            return View(roleList);
        }

        public IActionResult Details(int id)
        {
            RoleModel role = _roleService.Query().SingleOrDefault(r => r.Id == id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(RoleModel role)
        {
            if (ModelState.IsValid)
            {
                var result = _roleService.Add(role);
                if (result.IsSuccessfull)
                {
                    TempData["Message"] = result.Message;
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", result.Message);
            }
            return View(role);
        }

     

        public IActionResult Edit(int id)
        {
            RoleModel role = _roleService.Query().SingleOrDefault(r => r.Id == id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(RoleModel role)
        {
            if (ModelState.IsValid)
            {
                var result = _roleService.Update(role);
                if (result.IsSuccessfull)
                {
                    TempData["Message"] = result.Message; 
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", result.Message);
            }
            return View(role);
        }


        public IActionResult Delete(int id)
        {
             RoleModel role = _roleService.Query().SingleOrDefault(r => r.Id == id); // TODO: Add get item service logic here
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            // Debug statement to inspect ModelState
            foreach (var modelStateEntry in ModelState.Values)
            {
                foreach (var error in modelStateEntry.Errors)
                {
                    Console.WriteLine($"ModelState error: {error.ErrorMessage}");
                }
            }

            // Continue with deletion logic
            try
            {
                var result = _roleService.Delete(id);
                TempData["Message"] = result.Message;
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "An error occurred while deleting the role. Please try again later.";
                return RedirectToAction(nameof(Index)); // Redirect to a suitable action or view
            }
        }
    }
}

RMSCTIS/Controllers/UsersController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataAccess_.Contexts;
using DataAccess_.Entities;
using Business.Services;
using Business.Models;
using DataAccess_.Results.Bases;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using MVC.Controllers.Bases;



//Generated from Custom Template.
namespace MVC.Controllers
{
    public class UsersController : MvcControllerBase
	{
       
        private readonly IUserService _userService;
		private readonly IRoleService _roleService;

		public UsersController(IUserService userService, IRoleService roleService)
		{
			_userService = userService;
			_roleService = roleService;
		}

        [Authorize]
        public IActionResult GetList()
        {
           
            List<UserModel> userList = _userService.Query().ToList();
          
            return View("List", userList);
        }

        [Authorize(Roles = "admin")]

        public JsonResult GetListJson()
        {
            var userList = _userService.Query().ToList();
            return Json(userList);
        }

        public IActionResult Index()
        {
            List<UserModel> userList = _userService.Query().ToList();
            return View(userList);
        }

       
        public IActionResult Details(int id)
        {
            UserModel user = _userService.Query().SingleOrDefault(e=>e.Id ==id); 
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

      
        public IActionResult Create()
        {
          

			ViewData["RoleId"] = new SelectList(_roleService.Query().ToList(), "Id", "Name");
			return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(UserModel user)
        {
            if (ModelState.IsValid)
            {
                Result result = _userService.Add(user);
                if(result.IsSuccessfull)
                {
                   

                    TempData["Message"] = result.Message;
                    return RedirectToAction(nameof(Index));

                }

              

                ModelState.AddModelError("", result.Message);

               
            }
     
            ViewData["RoleId"] = new SelectList(new List<SelectListItem>(), "Value", "Text");
            return View(user);
        }


        public IActionResult Edit(int id)
        {
            UserModel user = _userService.Query().SingleOrDefault(e=> e.Id == id);
            if (user == null)
            {
                return NotFound();
            }
			// TODO: Add get related items service logic here to set ViewData if necessary
			var roleIds = _roleService.Query().Select(r => new SelectListItem
			{
				Value = r.Id.ToString(),
				Text = r.Name
			}).ToList();

			var selectedRoleId = user.RoleId.ToString();

			// Create a SelectList with the role IDs and set the selected value
			ViewData["RoleId"] = new SelectList(roleIds, "Value", "Text", selectedRoleId);

			return View(user);
			
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(UserModel user)
        {
            if (ModelState.IsValid)
            {
                Result result = _userService.Update(user);
                if(result.IsSuccessfull)
                {
                    TempData["Message"] = result.Message;
					return RedirectToAction(nameof(Details), new {id = user.Id});

				}
                ModelState.AddModelError("", result.Message);
			}
          
            ViewData["RoleId"] = new SelectList(new List<SelectListItem>(), "Value", "Text");
            return View(user);
        }

       
        public IActionResult Delete(int id)
        {
            UserModel user = _userService.Query().SingleOrDefault(e => e.Id == id); 
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
           Result result = _userService.Delete(id);
			TempData["Message"] = result.Message;
			return RedirectToAction(nameof(Index));
        }


    }


}

RMSCTIS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RMSCTIS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RMSCTIS.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RMSCTIS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated) 
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="GetList">User List</a>
                            </li>
                        }
                        @if (User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Role List</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Resources" asp-action="Index">Resource</a>
                        </li>
                      
                    </ul>

                    <div class="navbar-text">
                        <ul class="navbar-nav me-auto">

                          
                            @if (!User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                                </li>
                                <li class="nav-item">

                                    <a class="nav-link text-dark" asp-area="" asp-route="Register">Register</a>

                                </li>
                            }
                            else
                            {
                                <li class="nav-item pt-2">
                                    <span class="badge bg-info text-black">@User.Identity.Name</span>
                                </li>

                              
                                @:&nbsp;&nbsp;

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; @DateTime.Now.Year 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>